{
 "title": "Central Dash",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "up time" }
   ]
  },
  {
   "title": "Event Loop Lag p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "p99 event loop lag"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, route))",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[10m])) by (le, route))",
     "legendFormat": "Median {{route}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "Average {{route}}"
    }
   ]
  },
  {
   "title": "Node Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "RAM used" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "RAM total" }
   ]
  },
  {
   "title": "Active requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "active requests" }
   ]
  }
 ]
}