version: "3.3"

services:
  redis:
    container_name: sessions-cache
    image: redis:latest
    env_file:
      - dev.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis_db:/var/lib/redis/data
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"

  postgres:
    container_name: sessions-datastore
    image: postgres:13
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    user: postgres

volumes:
  postgres_db:
